services:
  centos7:
    image: centos:7
    container_name: centos7
    tty: true
    
  ubuntu:
    image: ubuntu
    container_name: ubuntu
    tty: true
    command: >
      bash -c "apt-get update && 
               apt-get install -y python3 && 
               tail -f /dev/null"

